CREATE TABLE F999CPL
   (	CODUSU INT(8) NOT NULL,
	TIPUSU VARCHAR(1) NOT NULL, 
	NOMUSU VARCHAR(255) NOT NULL,
	SENUSU VARCHAR(100),
	 CONSTRAINT CP_F999CPL PRIMARY KEY (CODUSU)
   );

CREATE TABLE F999GRP
   (	CODGRP INT(8) NOT NULL,
	DESGRP VARCHAR(100),
	 CONSTRAINT CP_F999GRP PRIMARY KEY (CODGRP)
   );

CREATE TABLE F999LIG
   (	CODGRP INT(8),
	CODUSU INT(8),
	SEQGRP INT(4) NOT NULL,
	 CONSTRAINT IRF99000 FOREIGN KEY (CODGRP)
	  REFERENCES F999GRP (CODGRP),
	 CONSTRAINT IRF99001 FOREIGN KEY (CODUSU)
	  REFERENCES F999CPL (CODUSU)
   );

CREATE TABLE F061DEP
   (	CODDEP INT(8) NOT NULL,
	DESDEP VARCHAR(100) NOT NULL,
	NOMRES VARCHAR(100),
	OBSDEP VARCHAR(1000),
	 CONSTRAINT CP_F061DEP PRIMARY KEY (CODDEP)
   );

CREATE TABLE F061ARE
   (	CODARE INT(8) NOT NULL,
	DESARE VARCHAR(100) NOT NULL,
	OBSARE VARCHAR(1000),
	CODDEP INT(8),
	 CONSTRAINT CP_F061ARE PRIMARY KEY (CODARE)
   );

CREATE TABLE F114CAB
   (	CODATN INT(8) NOT NULL,
	CODCLI INT(8) NOT NULL,
	CODATE INT(8) NOT NULL,
	CODUSU INT(8) NOT NULL,
	NIVPRI INT(4),
	CODDEP INT(8) NOT NULL,
	CODARE INT(8) NOT NULL,
	DATGER DATE NOT NULL,
	SITATN INT(2) NOT NULL,
	DATPRV DATE,
	DATATU DATE,
	DATFIM DATE,
	CODGRP INT(8) NOT NULL,
	NATATN INT(2),
	 CONSTRAINT CP_F114CAB PRIMARY KEY (CODATN),
	 CONSTRAINT IRF11004 FOREIGN KEY (CODUSU)
	  REFERENCES F999CPL (CODUSU),
	 CONSTRAINT IRF11002 FOREIGN KEY (CODCLI)
	  REFERENCES F999CPL (CODUSU),
	 CONSTRAINT IRF11001 FOREIGN KEY (CODDEP)
	  REFERENCES F061DEP (CODDEP),
	 CONSTRAINT IRF11000 FOREIGN KEY (CODARE)
	  REFERENCES F061ARE (CODARE)
   );

CREATE TABLE F114MSG
   (	CODATN INT(8) NOT NULL,
	SEQATN INT(4) NOT NULL,
	DESATN VARCHAR(1000),
	CODCLI INT(8) NOT NULL,
	CODATE INT(8) NOT NULL,
	SITATN INT(2) NOT NULL,
	DATATU DATE,
	CODUSU INT(8) NOT NULL,
	NIVPRI INT(4),
	 CONSTRAINT CP_F114MSG PRIMARY KEY (CODATN, SEQATN),
	 CONSTRAINT IRF11005 FOREIGN KEY (CODATN)
	  REFERENCES F114CAB (CODATN)
   );

CREATE TABLE F114IMG
   (	CODATN INT(8) NOT NULL,
	SEQATN INT(4) NOT NULL,
	SEQIMG INT(4) NOT NULL,
	IMGATN BLOB,
	EXTARQ VARCHAR(5),
	NOMARQ VARCHAR(100),
	 CONSTRAINT CP_F114IMG PRIMARY KEY (CODATN, SEQATN, SEQIMG),
	 CONSTRAINT IRF11006 FOREIGN KEY (CODATN, SEQATN)
	  REFERENCES F114MSG (CODATN, SEQATN)
   );
